Add 'Deploy to EKS' template to eks.yml workflow

diff --git a/azure-pipelines/templates/azure-devops/stages/install-kubectl.yml b/azure-pipelines/templates/azure-devops/stages/install-kubectl.yml
--- a/azure-pipelines/templates/azure-devops/stages/install-kubectl.yml
+++ b/azure-pipelines/templates/azure-devops/stages/install-kubectl.yml
@@ -1,32 +1,57 @@
 parameters:
+  - name: stageName
+    type: string
+
+  - name: dependsOn
+    type: string
+
   - name: k8sVersion
     type: string
 
 stages:
-  - stage: InstallKubectl
+  - stage: ${{ parameters.stageName }}
     displayName: Install kubectl
+    dependsOn: ${{ parameters.dependsOn }}
     jobs:
-      - job: DetectArch
-        displayName: Detect Linux Arch
+      - job: DetectDependencies
+        displayName: Check environment before kubectl installation
         steps:
-          
+
           - checkout: none
 
-          - bash: |
-              ARCH=$(uname -m)
-              case $ARCH in
-                x86_64) KUBECTL_ARCH="amd64" ;;
-                aarch64) KUBECTL_ARCH="arm64" ;;
-                *) echo "Unsupported architecture: $ARCH"; exit 1 ;;
-              esac
-              echo "##vso[task.setvariable variable=kubectl_arch;isOutput=true]${KUBECTL_ARCH}"
+         - task: Bash@3
+            name: kubectl
+            displayName: Check if kubectl already installed
+            inputs:
+              targetType: inline
+              script: |
+                if command -v kubectl >/dev/null 2>&1; then
+                  echo "kubectl exists"
+                  echo "##vso[task.setvariable variable=installed;isOutput=true]true"
+                else
+                  echo "kubectl not found"
+                  echo "##vso[task.setvariable variable=installed;isOutput=true]false"
+                fi
+
+         - task: Bash@3
             name: detect
+            displayName: Detect Linux architecture
+            inputs:
+              targetType: inline
+              script: |
+                ARCH=$(uname -m)
+                case $ARCH in
+                  x86_64) KUBECTL_ARCH="amd64" ;;
+                  aarch64) KUBECTL_ARCH="arm64" ;;
+                  *) echo "Unsupported architecture: $ARCH"; exit 1 ;;
+                esac
+                echo "##vso[task.setvariable variable=kubectl_arch;isOutput=true]${KUBECTL_ARCH}"
       
       - job: InstallKubectl
         displayName: Install kubectl
-        dependsOn: DetectArch
+        condition:  eq(dependencies.DetectDependencies.outputs['kubectl.installed'], 'false')
         variables:
-          kubectl_arch: $[ dependencies.DetectArch.outputs['detect.kubectl_arch'] ]
+          kubectl_arch: $[ dependencies.DetectDependencies.outputs['detect.kubectl_arch'] ]
         steps:
 
           - checkout: none
